# Generated by Django 2.2.6 on 2019-11-20 20:05

from django.db import migrations, models
import django.db.models.deletion
import jedzonko.models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(jedzonko.models.DayChoices('Monday'), 'Monday'), (jedzonko.models.DayChoices('Tuesday'), 'Tuesday'), (jedzonko.models.DayChoices('Wednesday'), 'Wednesday'), (jedzonko.models.DayChoices('Thursday'), 'Thursday'), (jedzonko.models.DayChoices('Friday'), 'Friday'), (jedzonko.models.DayChoices('Saturday'), 'Saturday'), (jedzonko.models.DayChoices('Sunday'), 'Sunday')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=24)),
                ('day_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedzonko.DayName')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedzonko.Plan')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedzonko.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='recipes',
            field=models.ManyToManyField(through='jedzonko.RecipePlan', to='jedzonko.Recipe'),
        ),
    ]
