# Generated by Django 2.2.7 on 2019-11-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0002_auto_20191120_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparing',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
