# Generated by Django 2.2.6 on 2019-11-21 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0009_auto_20191121_2357'),
        ('jedzonko', '0004_auto_20191121_1334'),
    ]

    operations = [
    ]
