# Generated by Django 2.2.7 on 2019-11-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0004_auto_20191121_1334'),
        ('jedzonko', '0009_auto_20191121_2357'),
    ]

    operations = [
    ]
