# Generated by Django 2.2.6 on 2019-11-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0010_merge_20191122_0012'),
        ('jedzonko', '0010_merge_20191123_1239'),
    ]

    operations = [
    ]
