# Generated by Django 2.2.7 on 2019-11-23 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0010_merge_20191123_1239'),
        ('jedzonko', '0010_merge_20191122_0012'),
    ]

    operations = [
    ]
