# Generated by Django 2.2.6 on 2019-11-24 22:39

from django.db import migrations, models
import jedzonko.models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0011_merge_20191124_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayname',
            name='name',
            field=models.CharField(choices=[(jedzonko.models.DayChoices('Monday'), 'Monday'), (jedzonko.models.DayChoices('Tuesday'), 'Tuesday'), (jedzonko.models.DayChoices('Wednesday'), 'Wednesday'), (jedzonko.models.DayChoices('Thursday'), 'Thursday'), (jedzonko.models.DayChoices('Friday'), 'Friday'), (jedzonko.models.DayChoices('Saturday'), 'Saturday'), (jedzonko.models.DayChoices('Sunday'), 'Sunday')], max_length=15),
        ),
    ]
