# Generated by Django 2.2.7 on 2019-11-26 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0011_merge_20191123_1257'),
        ('jedzonko', '0012_auto_20191124_2339'),
    ]

    operations = [
    ]
