# Generated by Django 2.2.6 on 2019-12-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0013_merge_20191126_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeplan',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
